version: '3.9'
services:
  db:
    image: postgres:13-alpine3.20
    restart: always
    container_name: backend_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: "test1234$"
      POSTGRES_DB: back_end_test
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3000:3000"

volumes:
  pg_data:
